-- Atlas Search — PostgreSQL schema

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  path TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS warehouses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),
  code TEXT NOT NULL,
  UNIQUE (warehouse_id, code)
);

-- Timestamps are stored as TEXT in UTC 'YYYY-MM-DD HH24:MI:SS' form rather than
-- as timestamptz. The API hands these strings to the frontend verbatim (the
-- admin order list parses them as `${value.replace(" ", "T")}Z`), so keeping the
-- exact wire format avoids a breaking change on every date the UI renders.
CREATE TABLE IF NOT EXISTS inventory_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id TEXT NOT NULL UNIQUE,
  -- Name, SKU, and category are optional: the admin form lets an item be saved
  -- with any subset of fields filled in. sku stays UNIQUE, and because NULLs
  -- don't collide in a unique index, any number of items may have none.
  sku TEXT UNIQUE,
  barcode TEXT,
  serial_number TEXT,
  name TEXT,
  brand TEXT,
  model TEXT,
  category_id INTEGER REFERENCES categories(id),
  warehouse_id INTEGER REFERENCES warehouses(id),
  location_id INTEGER REFERENCES locations(id),
  status TEXT NOT NULL DEFAULT 'Available',
  condition TEXT NOT NULL DEFAULT 'New',  -- 'New' or 'Used'
  quantity INTEGER NOT NULL DEFAULT 0,
  reserved_quantity INTEGER NOT NULL DEFAULT 0,
  reorder_point INTEGER NOT NULL DEFAULT 5,
  purchase_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  selling_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  description TEXT,
  ocr_text TEXT,
  icon TEXT,
  images TEXT,      -- JSON array of photo URLs, e.g. ["/uploads/a.jpg","/uploads/b.jpg"] — first is the main photo (falls back to icon+colors tile when empty)
  colors TEXT,      -- JSON array, e.g. ["#107c72","#5f6fb5"]
  tags TEXT,        -- JSON array, e.g. ["gaming pc","desktop"]
  custom_fields TEXT, -- JSON array of admin-defined {key, value} pairs for product-specific specs
  added_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  deleted_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_items_category ON inventory_items(category_id);
CREATE INDEX IF NOT EXISTS idx_items_warehouse ON inventory_items(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_items_status ON inventory_items(status);
CREATE INDEX IF NOT EXISTS idx_items_deleted ON inventory_items(deleted_at);

-- Full text search index (name, brand, model, sku, barcode, serial, tags, ocr,
-- description, category path). This replaces the old SQLite FTS5 virtual table:
-- the searchable columns are stored as plain text and Postgres derives the
-- tsvector from them in a generated column, so re-indexing an item is an
-- ordinary INSERT/UPDATE/DELETE and the GIN index keeps MATCH-style lookups
-- fast. 'english' mirrors the porter tokenizer FTS5 was configured with.
CREATE TABLE IF NOT EXISTS inventory_fts (
  item_id INTEGER PRIMARY KEY REFERENCES inventory_items(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  brand TEXT NOT NULL DEFAULT '',
  model TEXT NOT NULL DEFAULT '',
  sku TEXT NOT NULL DEFAULT '',
  barcode TEXT NOT NULL DEFAULT '',
  serial_number TEXT NOT NULL DEFAULT '',
  tags TEXT NOT NULL DEFAULT '',
  ocr_text TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  category_path TEXT NOT NULL DEFAULT '',
  document tsvector GENERATED ALWAYS AS (
    to_tsvector(
      'english',
      name || ' ' || brand || ' ' || model || ' ' || sku || ' ' || barcode || ' ' ||
      serial_number || ' ' || tags || ' ' || ocr_text || ' ' || description || ' ' || category_path
    )
  ) STORED
);

CREATE INDEX IF NOT EXISTS idx_fts_document ON inventory_fts USING GIN (document);

CREATE TABLE IF NOT EXISTS search_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query TEXT,
  audience TEXT NOT NULL DEFAULT 'admin', -- admin | shop
  result_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

-- ---------------------------------------------------------------------------
-- Storefront customer accounts
--
-- Separate from the admin console, which stays on its single shared password.
-- Email is stored lower-cased and is the login identifier.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  -- scrypt$N$r$p$salt$hash — never a raw or reversible value. NULL for accounts
  -- created through Google sign-in, which have no password at all; those sign in
  -- through the provider, and a NULL here is what marks that.
  password_hash TEXT,
  name TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_login_at TEXT,
  -- Until this is set the account exists but cannot sign in: registration only
  -- completes once the emailed code proves the address belongs to the person.
  email_verified_at TEXT,
  password_changed_at TEXT,
  -- Google's stable subject id. Preferred over the email address for matching a
  -- returning customer, because a person can change the address on their Google
  -- account but never this.
  google_sub TEXT UNIQUE,
  -- Two-step verification (TOTP). The secret is what the authenticator app
  -- holds; recovery_codes is a JSON array of SHA-256 hashes, never the codes.
  totp_secret TEXT,
  totp_enabled_at TEXT,
  recovery_codes TEXT,
  -- Unix seconds. Access tokens are stateless and valid for 15 minutes, so
  -- revoking refresh tokens alone would leave a signed-out device working until
  -- its access token happened to expire. Every token issued before this instant
  -- is rejected, which makes "sign out everywhere" actually immediate.
  -- Milliseconds, so BIGINT: a millisecond epoch overflows a 4-byte integer.
  sessions_valid_from BIGINT
);

-- Emailed one-time codes for verifying an address and resetting a password.
-- Only the hash is stored, so the table holds nothing that can be typed into
-- the app. Codes are single use, expire, and stop accepting guesses after a
-- handful of wrong attempts.
CREATE TABLE IF NOT EXISTS auth_codes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL,  -- 'verify' | 'reset'
  code_hash TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_auth_codes_user ON auth_codes(user_id, purpose);

-- Refresh tokens live here, never in the browser in readable form: the cookie
-- carries a random secret and only its SHA-256 hash is stored, so a dump of
-- this table cannot be replayed as a login.
--
-- Rotation: every refresh issues a new row and marks the old one used. All
-- tokens descended from one login share a family_id, so if a token that was
-- already used comes back (i.e. it leaked and someone is replaying it) the
-- whole family is revoked and that session is forced to log in again.
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  family_id TEXT NOT NULL,
  issued_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  expires_at TEXT NOT NULL,
  used_at TEXT,
  revoked_at TEXT,
  last_used_at TEXT,
  user_agent TEXT,
  ip TEXT
);

CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_family ON refresh_tokens(family_id);
CREATE INDEX IF NOT EXISTS idx_refresh_expires ON refresh_tokens(expires_at);

-- One row per product in a customer's basket. The unique constraint is what
-- makes "click Buy twice" add up instead of creating a second line.
-- Prices deliberately live only on inventory_items: the basket total is
-- recomputed from current prices on every read, never stored or trusted from
-- the client.
CREATE TABLE IF NOT EXISTS cart_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  inventory_item_id INTEGER NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  added_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (user_id, inventory_item_id)
);

CREATE INDEX IF NOT EXISTS idx_cart_user ON cart_items(user_id);

-- ---------------------------------------------------------------------------
-- Orders
--
-- One row here per order the customer actually placed, and one row in
-- order_items per product line within it. The earlier shape had no parent row
-- at all — a three-product basket became three independent rows that could
-- only be reassembled by grouping on an identical timestamp, which meant the
-- shop could not name an order, total it, give it a status, or record that it
-- had been paid for.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- What the customer quotes and support searches for. Random, not sequential:
  -- see lib/orders.js.
  order_number TEXT NOT NULL UNIQUE,

  user_id INTEGER REFERENCES users(id),  -- the buyer; NULL for orders placed before accounts existed

  -- See ORDER_STATUSES in lib/orders.js for what each value means. Every order
  -- starts 'pending' and stays there until a payment confirms it.
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'paid', 'shipped', 'cancelled', 'refunded')),

  -- A whole number of minor units (cents), never a float — see toMinor() in
  -- lib/orders.js for why. Recomputed from the lines at write time and stored,
  -- because what the customer agreed to pay must not move when a price does.
  total_minor BIGINT NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',

  -- The payment provider's own identifier, so a row here can be matched
  -- against their dashboard during a dispute. NULL until a payment exists.
  payment_ref TEXT,

  -- Sent by the client and unique per order, so a retried request — a
  -- double-click, a flaky connection, a provider replaying its webhook —
  -- returns the order that was already placed instead of placing a second one.
  idempotency_key TEXT UNIQUE,

  -- Where the order is going, snapshotted at checkout for the same reason the
  -- product fields are: a customer who moves house must not retroactively
  -- change where last month's parcel was sent. Nullable because orders
  -- migrated from the old flat table never collected any of it, and because a
  -- 'pickup' order has no address to collect — see normaliseDelivery() in
  -- lib/orders.js, which is where "required" is actually decided.
  delivery_method TEXT NOT NULL DEFAULT 'delivery'
    CHECK (delivery_method IN ('delivery', 'pickup')),
  ship_name TEXT,
  ship_phone TEXT,
  ship_country TEXT,
  ship_city TEXT,
  ship_line1 TEXT,
  ship_line2 TEXT,
  ship_postal_code TEXT,
  ship_notes TEXT,

  placed_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_orders_placed_at ON orders(placed_at);
CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

-- One product line. The product fields are snapshots taken when the order was
-- placed, so history stays accurate even if the item is later renamed,
-- repriced or deleted — which is also why the text columns are duplicated here
-- rather than joined from inventory_items at read time.
CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  inventory_item_id INTEGER NOT NULL REFERENCES inventory_items(id),
  -- Snapshots of fields that are themselves optional on the item.
  sku TEXT,
  name TEXT,
  brand TEXT,
  model TEXT,
  category TEXT,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  -- Price of one unit, in minor units. The line total is this times quantity;
  -- it is not stored, because a stored copy is one more thing to disagree.
  unit_price_minor BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_item ON order_items(inventory_item_id);

-- ---------------------------------------------------------------------------
-- Display exchange rates
--
-- The shop prices and charges in USD. These exist so a customer can see
-- roughly what something costs in their own money — they are a convenience,
-- not a price, and the storefront labels converted figures as approximate.
--
-- In the database rather than in the frontend because a rate that lives in
-- JavaScript can only be corrected by editing code, rebuilding and deploying.
-- A shop needs to be able to fix a wrong rate in a minute, and to see
-- afterwards who changed it and when.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exchange_rates (
  -- ISO 4217, upper case. USD is the base and is always exactly 1.
  code TEXT PRIMARY KEY,
  -- How many units of `code` one US dollar buys.
  rate DOUBLE PRECISION NOT NULL CHECK (rate > 0),
  -- Which admin last touched it. Text, not a foreign key: admins live in the
  -- environment, not in a table.
  updated_by TEXT,
  updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

-- One row per day recording what the dashboard tiles read, so the console can
-- show movement and not just a current figure.
--
-- This has to be recorded as it happens: inventory_items keeps only added_at /
-- updated_at / deleted_at, and quantity and price are overwritten in place, so
-- "what was stock worth last Tuesday" is not recoverable after the fact.
--
-- captured_on is the primary key and writes upsert into it, so a day gets one
-- row holding its most recent reading however often the server restarts.
CREATE TABLE IF NOT EXISTS inventory_snapshots (
  captured_on DATE PRIMARY KEY,
  inventory_value DOUBLE PRECISION NOT NULL DEFAULT 0,
  stock_count INTEGER NOT NULL DEFAULT 0,
  low_stock_count INTEGER NOT NULL DEFAULT 0,
  item_count INTEGER NOT NULL DEFAULT 0,
  captured_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);
